version: "3"

services:
  backend:
    build:
      context: backend
    ports:
      - "5001:80"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=80
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app

  example_app:
    build: example_app
    ports:
      - "5002:5003"
    volumes:
      - ./example_app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_PORT=5003
      - FLASK_DEBUG=1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: backend
    hostname: worker
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    depends_on:
      - redis
